### ISSUE TITLE
Error while loading latest Yes Already

### ISSUE THREAD

**Issue by drejjmit** [daemitus/YesAlready#89]
Getting this error with latest version:
```
2023-01-11 08:33:11.907 +01:00 [ERR] [LOCALPLUGIN] Error while loading Yes Already
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: [FFXIVClientStructs.Resolver] Attempted to call Resolve() without initializing the search space.
   at FFXIVClientStructs.Interop.Resolver.Resolve() in D:\a\YesAlready\YesAlready\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 182
   at ClickLib.Click.Initialize()
   at YesAlready.YesAlreadyPlugin..ctor(DalamudPluginInterface pluginInterface)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 104
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 421
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 871
```
Yes Already v1.3.0.1

**Comment by guppyfaced** [comment]
Using UnloadError(Begone) plugin, I was able to hot-reload it and it seems to be working as before.

**Comment by Helios747** [comment]
Can reproduce, same error.

**Comment by daemitus** [comment]
fix for the `Resolve()` issue coming. Let me know if any sigs blow up, im
not subbed atm.

**Comment by Helios747** [comment]
Latest build installs correctly for me. A quick test of materia extraction and GC vending works as expected. Custom text detection works as expected.

**Comment by daemitus** [comment]
All the sigs resolved to a single address, so provided the offsets are all
good. This might be good until the next major  patch :D

**Comment by drejjmit** [comment]
Working 👍
Thanks for keeping your plugins updated even to you're not subbed. 
Can't live without them xD

**Comment by guppyfaced** [comment]
working 100% for me too
